services:
  dgraph:
    image: dgraph/standalone
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-IL", "localhost:6080/state"]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 3

  graphql:
    build:
      dockerfile: graphql/Dockerfile
      target: production
    tty: true
    depends_on:
      dgraph:
        condition: service_healthy
    expose:
      - 8080

  test-graphql:
    build:
      dockerfile: graphql/Dockerfile
      target: test
    depends_on:
      - graphql

  test-gql-client:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: gql-client
    depends_on:
      - graphql

  test-database:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: database
    depends_on:
      - graphql

  test-poll:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: poll
    depends_on:
      - graphql

  test-update:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: update
    depends_on:
      - graphql

  test-rank:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: rank
    depends_on:
      - graphql
