services:
  poll:
    build:
      dockerfile: config/python/Dockerfile
      target: production
      args:
        project: poll

  update:
    build:
      dockerfile: config/python/Dockerfile
      target: production
      args:
        project: update
    ports:
      - "8001:8001/tcp"

  rank:
    build:
      dockerfile: config/python/Dockerfile
      target: production
      args:
        project: rank
    ports:
      - "8002:8002/tcp"

  database:
    build:
      dockerfile: config/python/Dockerfile
      target: production
      args:
        project: database
    ports:
      - "8003:8003/tcp"
