services:
  database-test:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: database

  poll-test:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: poll
    depends_on:
      database-test:
        condition: service_completed_successfully

  update-test:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: update
    depends_on:
      poll-test:
        condition: service_completed_successfully

  rank-test:
    build:
      dockerfile: config/python/Dockerfile
      target: test
      args:
        project: rank
    depends_on:
      update-test:
        condition: service_completed_successfully
